const header = document.querySelector("li");
header.remove();
const readm = document.querySelector('span');
readm.remove();
const readmy = document.querySelector('main .posts article');
readmy.remove();
const readmyp = document.querySelector('main .posts h3');
readmyp.remove();
const readmypg = document.querySelector('main .posts h3');
readmypg.remove();
